### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by Assassin654** [leifadev/scout#1]
VideoPrivate: is not defined. line 229. and I'm assuming all the ones under it. when I marked it out it went on to the next one.
Windows 10
id also recommend maybe adding something like this to the top 

try:
  from pytube import YouTube
except ImportError:
  print ("Trying to Install required module: requests\n")
  os.system('pip3 install pytube3')

that way people don't have to install manually

**Comment by leifadev** [comment]
try v1.2, i fixed the error handling and functions, i will add that as well

**Comment by leifadev** [comment]
Also, its fixed and the binaries are self-bootstrapping with pyinstaller, let me know if there are more issues.
Also, I abandoned pytube3 as it had limited exceptions to handle with
