### ISSUE TITLE
README Issue

### ISSUE THREAD

**Issue by TabulateJarl8** [leifadev/scout#15]
The README says that this program has been tested to work on Python versions 3.7-9.2. This isn't entirely possibly considering the fact that there are no major Python versions past 3. I'm not entirely sure what the correct version number would be, so that's why I'm making an issue instead of a pull request.

**Comment by leifadev** [comment]
Ok, right now Im busy and it's easier to just say python 3. I was using python 3.9.2 on my Windows machine with building and running the scripts and what not
