### ISSUE TITLE
Code is unnecessarily repeated across different os versions 

### ISSUE THREAD

**Issue by KrazyKirby99999** [leifadev/scout#2]
The entire app is rewritten for each os. It would be better to create an interface in which the os-unique code and the common code are separate.

**Comment by KrazyKirby99999** [comment]
Pull request #3 should solve this isse.

**Comment by KrazyKirby99999** [comment]
The pull request is essentially a merge, but the maintainer of the receiving repo must approve it. 

"interface in which the os-unique code and the common code are separate" - the common code would be written once, with the os-specific code being replaced by variables. Those variables would be changed depending upon the os.

**Comment by leifadev** [comment]
I see now, I had trouble merging your changes, but I will add them manually with copy paste as well as more research, thanks!

**Comment by KrazyKirby99999** [comment]
The solution for this issue was reverted in https://github.com/leifadev/scout/commit/186c2b4b2c93930c7369246549dbdb069dd3cda1. Was this intentional?
