### ISSUE TITLE
Lack of Makefile

### ISSUE THREAD

**Issue by KrazyKirby99999** [leifadev/scout#6]
I would recommend creating a makefile to assist contributors with building, testing, and contributing.

**Comment by leifadev** [comment]
does this have to have a certain lang/syntax or can it be a python file (I would rather have it bee python)

**Comment by KrazyKirby99999** [comment]
It must follow the Makefile syntax, and have the name "Makefile" with no extension. Here is an example - https://raw.githubusercontent.com/KrazyKirby99999/python-project-template/master/Makefile

Makefile(s) allow you to set custom scripts for your project easily. You can set a command to upload your project to pypi, build your project, clean unwanted build files, or anything else that can be done with the command line.

**Comment by leifadev** [comment]
Ok, ill take from the example and may add pyinstallers stuff to it

**Comment by leifadev** [comment]
Btw, do I have do do smth with `{PYTHON}` as having it be defined by me, or should I just leave it alone?
	
`${PYTHON} -m pip install -r requirements.txt`

**Comment by KrazyKirby99999** [comment]
The {PYTHON} is a variable, so it is best to use it whenever you can. Otherwise, contributors who have different commands for python (python/python3/python3.9/etc) may have to modify the Makefile in many places, instead of once.

**Comment by KrazyKirby99999** [comment]
"${PYTHON} -m pip install -r requirements.txt" appears fine.

**Comment by KrazyKirby99999** [comment]
I would like to point out that the current Makefile uses nuitka as a compiler, instead of pyinstaller, and uses nose2 to test, even though you have not implemented testing. You may want to comment out and modify parts of the Makefile.

**Comment by leifadev** [comment]
Ok I got you, was gonna get pyinstaller in there but didnt have time to look into that, I'll switch that out in a bit, thanks my dude
