### ISSUE TITLE
Unnecessary Entries in requirements.txt

### ISSUE THREAD

**Issue by KrazyKirby99999** [leifadev/scout#7]
This is the requirements.txt file. The program is able to run without errors with only the requirements that are commented with the exception of pyinstaller. 
```
#     altgraph==0.17
#     certifi==2020.12.5
#     macholib==1.14
pyinstaller==4.2
#     pyinstaller-hooks-contrib==2021.1
pytube==10.6.0
#     PyYAML==5.4.1
ruamel.yaml==0.16.13
#     ruamel.yaml.clib==0.2.2
#     typing-extensions==3.7.4.3
wget==3.2
```

**Comment by KrazyKirby99999** [comment]
The rest of the entries appear unnecessary.

**Comment by leifadev** [comment]
Oh I see thanks will look into that

**Comment by leifadev** [comment]
Aren't you saying thta the uncommented ones would need to be? Pytube or ruamel or example aren't preinstalled on a OS

**Comment by KrazyKirby99999** [comment]
Thanks, that was a mistake. The uncommented lines are the necessary lines.

**Comment by leifadev** [comment]
Ok makes more sense, I'll remember this
