### ISSUE TITLE
README includes Windows 8 as a platform

### ISSUE THREAD

**Issue by KrazyKirby99999** [leifadev/scout#8]
The readme file includes a row for Windows 8, which is unnecessary because very few users use Windows 8. According to this [website](https://gs.statcounter.com/windows-version-market-share/desktop/worldwide/), less than 5% of windows users use Windows 8, which comes out to less than 1.5% of users across all operating systems.
| Windows 8 | ?                |

**Comment by KrazyKirby99999** [comment]
There is also a mistake in the readme, "macOS version" should be replaced by "Operating System" or "OS".
![image](https://user-images.githubusercontent.com/69373044/113373260-12ea7280-9330-11eb-8861-e6a194b83aa1.png)

**Comment by KrazyKirby99999** [comment]
To summarize, "macOS Version" should be replaced by "Operating System", and the "Windows 8" row should be removed.

**Comment by leifadev** [comment]
Oh ok lol I just put it there just in case. thanks for that macos thing :)
